# Generated by Django 4.0.3 on 2022-04-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operatingsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('software_license', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('platforms', models.CharField(max_length=100)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatingsystem.operatingsystem')),
            ],
        ),
    ]
